use_frameworks!

target 'NgFramework_Example' do
  pod 'NgFramework', :path => '../'

  target 'NgFramework_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.0.0'
  pod 'Nimble', '~> 5.1.1'
  end
end
